// lib/albums.data.js
// Tambah, hapus, atau ubah album cukup dari file ini.
// Pastikan image diarahkan ke file di folder public/albums.

export const CATEGORIES = [
  "Semua",
  "Produk",
  "Diskon",
  "Undangan",
  "Hari Spesial",
  "Perusahaan",
  "Politik",
];

export const PROJECTS = [
  {
    id: 1,
    category: "Produk",
    title: "Neon Beast Energy Drink",
    desc: "Banner promosi penjualan produk retail dengan visual 3D pop-out.",
    code: "NB-01",
    palette: ["#B9FF00", "#151515", "#FF3D00"],
    image: "/albums/album-01.webp",
  },
  {
    id: 2,
    category: "Diskon",
    title: "Black Friday Cyber Sale",
    desc: "Desain ads retail e-commerce dengan tipografi kinetik.",
    code: "BF-02",
    palette: ["#FF00E5", "#0B0B0F", "#B9FF00"],
    image: "/albums/album-02.webp",
  },
  {
    id: 3,
    category: "Undangan",
    title: "The Royal Heritage Wedding",
    desc: "Undangan digital premium dengan aksen batik Cirebon modern.",
    code: "RH-03",
    palette: ["#C8A45D", "#2A1710", "#FFF4D6"],
    image: "/albums/album-03.webp",
  },
  {
    id: 4,
    category: "Hari Spesial",
    title: "Eid Mubarak Canvas Identity",
    desc: "Ucapan hari besar korporat dengan teknik vector-shading.",
    code: "EM-04",
    palette: ["#00D084", "#083B2D", "#F5E8C7"],
    image: "/albums/album-04.webp",
  },
  {
    id: 5,
    category: "Perusahaan",
    title: "Astra Media Rebranding",
    desc: "Corporate identity kit, logo, dan panduan warna.",
    code: "AM-05",
    palette: ["#E7E0CF", "#171411", "#FFB800"],
    image: "/albums/album-05.webp",
  },
  {
    id: 6,
    category: "Politik",
    title: "Suara Muda 2029 Campaign",
    desc: "Poster komunikasi politik dan infografis publik berbasis tipografi berani.",
    code: "SM-06",
    palette: ["#FF3D00", "#F4ECD8", "#111111"],
    image: "/albums/album-06.webp",
  },
  {
    id: 7,
    category: "Produk",
    title: "Volta Sneakers Launch",
    desc: "Instagram feed layout untuk peluncuran sepatu lokal.",
    code: "VS-07",
    palette: ["#B9FF00", "#5433FF", "#0E0E0E"],
    image: "/albums/album-07.webp",
  },
  {
    id: 8,
    category: "Produk",
    title: "SmartHub QYEN Launch Promo",
    desc: "Poster promosi untuk ekosistem smart home SmartHubQyen dengan fokus dashboard, automasi, dan monitoring energi.",
    code: "QY-08",
    palette: ["#B9FF00", "#171411", "#F4ECD8"],
    image: "/albums/album-08.webp",
  },
  {
    id: 9,
    category: "Undangan",
    title: "Gala Creative Night 2026",
    desc: "Tiket dan undangan fisik konser musik luring eksklusif.",
    code: "GC-09",
    palette: ["#F7D060", "#151515", "#7D5FFF"],
    image: "/albums/album-09.webp",
  },
  {
    id: 10,
    category: "Hari Spesial",
    title: "Merdeka Creative Campaign",
    desc: "Visual kemerdekaan RI bergaya pop-art untuk brand FnB.",
    code: "MC-10",
    palette: ["#E60012", "#FFFFFF", "#111111"],
    image: "/albums/album-10.webp",
  },
  {
    id: 11,
    category: "Perusahaan",
    title: "QYEN Studio Stationery",
    desc: "Desain kartu nama, amplop, dan merchandise kreatif.",
    code: "QS-11",
    palette: ["#F4ECD8", "#171411", "#B9FF00"],
    image: "/albums/album-11.webp",
  },
  {
    id: 12,
    category: "Politik",
    title: "Green City Manifesto",
    desc: "Kampanye lingkungan hidup untuk poster baliho daerah.",
    code: "GC-12",
    palette: ["#4ADE80", "#072E1A", "#F4ECD8"],
    image: "/albums/album-12.webp",
  },
];
